FROM postgres:16

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        git \
        make \
        gcc \
        libpq-dev \
        postgresql-server-dev-all \
    && git clone https://github.com/ossc-db/pg_bigm.git \
    && cd pg_bigm \
    && make \
    && make install \
    && cd .. \
    && rm -rf pg_bigm \
    && apt-get remove -y git make gcc libpq-dev postgresql-server-dev-all ca-certificates \
    && apt-get autoremove -y \
    && apt-get clean

EXPOSE 5432
